package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"os"
	"strings"
)

func process(
	r io.Reader,
	outputName string,
	oldImportPath string,
	newImportPath string,
) error {
	fset := token.NewFileSet()

	// Parse from reader
	file, err := parser.ParseFile(fset, outputName, r, parser.ParseComments)
	if err != nil {
		return err
	}

	file.Name.Name = "chroma"

	ast.Inspect(file, func(n ast.Node) bool {
		imp, ok := n.(*ast.ImportSpec)
		if !ok {
			return true
		}

		// replace old import with new import
		imp.Path.Value = strings.ReplaceAll(
			imp.Path.Value,
			oldImportPath,
			newImportPath,
		)

		return false
	})

	out, err := os.Create("zz_" + outputName)
	if err != nil {
		return err
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by go run ./generate/ DO NOT EDIT.")
	fmt.Fprintln(out)

	return printer.Fprint(out, fset, file)
}
